ptz:
  name: PTZ
  description: Pan and tilt camera
  target:
    entity:
      domain: camera
      integration: tapo_control
  fields:
    tilt:
      description: "Tilt direction."
      example: "UP"
      name: Tilt
      selector:
        select:
          options:
            - "UP"
            - "DOWN"
    pan:
      name: Pan
      description: "Pan direction."
      example: "RIGHT"
      selector:
        select:
          options:
            - "RIGHT"
            - "LEFT"

save_preset:
  name: Save preset
  description: Saves the current PTZ position to a preset
  target:
    entity:
      domain: camera
      integration: tapo_control
  fields:
    name:
      description: "Name of the preset."
      example: "Entry Door"
      required: true
      name: Name
      selector:
        text:
delete_preset:
  name: Delete preset
  description: Deletes a preset
  target:
    entity:
      domain: camera
      integration: tapo_control
  fields:
    preset:
      description: "PTZ preset ID or a Name. See possible presets in entity attributes"
      example: "1"
      required: true
      name: Name
      selector:
        text:
